#!/bin/bash -e
# easy remote execution of projects in patan.act.uji.es
# 	source		https://github.com/MAProsper/patan-run
# 	developer	Miguel Ángel Prosper Quíros	(al386125@uji.es)
# 	tester		Paul Ximo Pluijter Izquierdo	(al386152@uji.es)
# 	tester		Adrián Masiá Moreno		(al386159@uji.es)
# 	tester		Adrián Luque Bueso		(al387532@uji.es)
# 	license		BSD 3-Clause
# 	version		6.1.0

info() { echo "$NAME: $*" >&2; }; err() { info "$*"; exit 1; }; arg() { printf '%q ' "$@"; }
NAME='patan-run'; VAR="$(arg "$@")"; TYPE="$2"; ID="${ID-$(date +%F-%H-%M-%S)}"
TMP=".$NAME-$ID"; JOB="$TMP/$TYPE"; ORG=".local/state/$NAME/$ID"

#!/man/patan-run
# user type [args...]	(cd to project's root first)
# 	user	al386125	(skip username if installed)
# 	type	java, ...	(type of action or project)
# 	args	...		(type specific arguments)

#!/usr/patan-run
SERVER="$1@patan.act.uji.es"; PROXY="${PROXY-$1}@lynx.uji.es"; SCP="$HOME/.ssh/$NAME"; TMOUT="${TMOUT-256}"
EXE="$HOME/.local/bin/$NAME"; ENV="${ENV-$HOME/.${SHELL##*/}rc}"; RC="alias '$NAME=$(arg "$EXE")$1'"
SSH="ssh -o PreferredAuthentications=password -o ControlPersist=$TMOUT -XS $SCP -J $PROXY $SERVER"
exe() { echo "set -- $VAR; ID=$ID"; tuc 'bin' 'bash'; tuc "$1" "$NAME"; tuc "$1"; }
rmc() { [ -f "$ENV" ] && grep -v "^${RC%%/*}" <<<"$(<"$ENV")" >"$ENV" || :; }
ret() { err 'restart terminal to finish'; }; nul() { "$@" &>'/dev/null'; }
tuc() { sed -E "\~^#!/$1/${2:-$TYPE}([[:space:]]|$)~,/^#!/!d;//d" "$0"; }
cpx() { mkdir -p "${1%/*}"; [ "$0" -ef "$1" ] || install "$0" "$1"; }
man() { err "$(tuc "${2-man}" "$1" | sed -n 's/# //p')"; }

# validate arguments
[ "$BASH_SOURCE" = "$0" ]	|| err 'must execute directly locally'
[ $# -ge 2 ]			|| man "$NAME"
[[ "$1" =~ ^[a-z0-9]+$ ]]	|| err 'username not valid'
[ "$(tuc usr; tuc srv)" ]	|| err 'type not supported'

# main fragment
. '/dev/stdin' <<<"$(tuc usr)"
nul $SSH -O 'check' || { rm -f "$SCP"; MCP='-M'; }
trap 'rm -r "$TMP"' EXIT; cpx "$JOB"; exe 'job' >"$_"
info "$PWD"; PREV=$($SSH "$MCP" "mkdir -p .ssh $ORG; ls \$_/.. | sed 'x;\$!d'")
info 'transferring workspace'; rsync -ae "$SSH" --link-dest="../$PREV" './' ":$ORG"
$SSH -qt "$(exe srv)"; exit

#!/srv/patan-run
cd "$ORG"; QSUB="qsub -${DISPLAY+X}Ix $PWD/$JOB"; LOG="$TMP/log"
job() { info "$VAR" &>"$LOG"; script -qac "$QSUB $(arg "$@")" "$LOG"; }

#!/job/patan-run
cd "$PBS_O_WORKDIR"; trap 'info "exit code $?"' EXIT

#!/usr/version
man 'bash' 'bin'

#!/usr/install
rmc; echo "$RC" >>"$ENV"; cpx "$EXE"; ret

#!/usr/remove
rmc; rm "$0"; ret

#!/srv/ssh
[ $# -ge 3 ]	|| "$SHELL"
[ $# -ge 3 ]	&& "$SHELL" -c "$(arg "${@:3}")"

#!/man/java
# main [args...]
# 	main	package.class	(main method's class name)
# 	args	...		(program arguments)

#!/usr/java
[ $# -ge 3 ]	|| man
[ "$3" ]	|| err 'main class cannot be empty'

#!/srv/java
job -q 'epyc' -l 'nodes=1:ppn=16'

#!/job/java
find '.' -name '*.java' -exec javac -encoding 'UTF-8' -d "$TMP" '{}' '+'
java -cp "$TMP" "${@:3}"

#!/man/mpi
# main nodes [args...]
# 	main	main.c	(main file's relative path)
# 	nodes	16	(number of nodes to utilize)
# 	args	...	(program arguments)

#!/usr/mpi
[ $# -ge 4 ]		|| man
[ -f "$3" ]		|| err 'main file not found'
[[ "$4" =~ ^[0-9]+$ ]]	|| err 'nodes must be positive integer'

#!/srv/mpi
job -q 'bi' -l "nodes=$4:ppn=4"

#!/job/mpi
EXE="$TMP/exe"; NODE="$TMP/node"
uniq "$PBS_NODEFILE" >"$NODE"; mpicc "$3" -o "$EXE"
mpirun -mca 'btl_tcp_if_include' 'eth0' -np "$4" -machinefile "$NODE" "$EXE" "${@:5}"